services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - 8080:8080
    networks:
      - monitoring
    container_name: cadvisor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command: '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - monitoring
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  
  grafana:
    image: grafana/grafana
    user: "1000"
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./grafana:/etc/grafana/provisioning/datasources
  
  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - 9093:9093
    networks:
      - monitoring
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager-data:/data
    command: --config.file=/etc/alertmanager/alertmanager.yml --cluster.advertise-address=0.0.0.0:9093
        #- '--storage.path=/alertmanager'
    
  discord-alerts:
    image: benjojo/alertmanager-discord
    container_name: discord-alerts
    restart: unless-stopped
    environment:
      - DISCORD_WEBHOOK=https://discordapp.com/api/webhooks/1171520305617973328/gX2L1I2Dwpm6zn0tbG2NuDbQephJnizdrzDJWVCYKwNuw06sPc_gZWV7Y9cwmDEsS0MJ
    ports:
      - 9094:9094
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  prom_data:
  alertmanager-data: